"use client";

import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { Skeleton } from "@/components/ui/Skeleton";
import { PayslipData } from "@/types/payroll";
import { formatCurrency } from "@/lib/utils";

interface PayslipModalProps {
  open: boolean;
  loading: boolean;
  payslip: PayslipData | null;
  onClose: () => void;
}

export const PayslipModal = ({
  open,
  loading,
  payslip,
  onClose,
}: PayslipModalProps) => {
  const handlePrintPdf = () => {
    if (!payslip || typeof window === "undefined") {
      return;
    }

    const printWindow = window.open("", "_blank", "width=900,height=1200");
    if (!printWindow) {
      return;
    }

    const deductionsRows = `
      <tr><td>PF</td><td>${formatCurrency(payslip.pf)}</td></tr>
      <tr><td>ESI</td><td>${formatCurrency(payslip.esi)}</td></tr>
      <tr><td>PT</td><td>${formatCurrency(payslip.pt)}</td></tr>
      <tr><td>TDS</td><td>${formatCurrency(payslip.tds)}</td></tr>
      <tr><td>Meals</td><td>${formatCurrency(payslip.meals)}</td></tr>
    `;

    const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Alicesoft Payslip - ${payslip.employeeName}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; color: #111827; }
    .sheet { border: 1px solid #d1d5db; border-radius: 14px; padding: 20px; }
    .head { display: flex; justify-content: space-between; align-items: center; gap: 16px; border-bottom: 1px solid #e5e7eb; padding-bottom: 16px; margin-bottom: 16px; }
    .brand { display: flex; align-items: center; gap: 12px; }
    .brand img { width: 56px; height: 56px; }
    .brand h1 { margin: 0; font-size: 24px; }
    .sub { color: #6b7280; margin: 0; font-size: 13px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
    .panel { border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }
    .panel h3 { margin: 0 0 8px 0; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    td { border-bottom: 1px solid #eef2f7; padding: 6px 0; }
    td:last-child { text-align: right; font-weight: 600; }
    .totals { display: grid; gap: 8px; margin-top: 12px; }
    .totals p { margin: 0; display: flex; justify-content: space-between; font-size: 14px; }
    .net { font-size: 18px; font-weight: 700; color: #0f766e; }
    .footer { display: flex; justify-content: space-between; margin-top: 24px; color: #6b7280; font-size: 12px; }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="head">
      <div class="brand">
        <img src="${window.location.origin}/alicesoft-logo.png" alt="Alicesoft Logo" />
        <div>
          <h1>Alicesoft</h1>
          <p class="sub">Salary Payslip</p>
        </div>
      </div>
      <div>
        <p class="sub">Period: ${payslip.month}</p>
        <p class="sub">Employee ID: ${payslip.employeeId}</p>
      </div>
    </div>

    <div class="grid">
      <div class="panel">
        <h3>Employee Details</h3>
        <table>
          <tr><td>Name</td><td>${payslip.employeeName}</td></tr>
          <tr><td>Role</td><td>${payslip.role}</td></tr>
          <tr><td>Salary Model</td><td>${payslip.salaryModel}</td></tr>
          <tr><td>Total Minutes</td><td>${payslip.totalMinutes}</td></tr>
          <tr><td>Meals Consumed</td><td>${payslip.mealsConsumed}</td></tr>
        </table>
      </div>

      <div class="panel">
        <h3>Deductions</h3>
        <table>${deductionsRows}</table>
      </div>
    </div>

    <div class="panel">
      <h3>Payroll Summary</h3>
      <div class="totals">
        <p><span>Gross</span><span>${formatCurrency(payslip.gross)}</span></p>
        <p><span>Total Deductions</span><span>${formatCurrency(payslip.deductions)}</span></p>
        <p class="net"><span>Net Pay (INR)</span><span>${formatCurrency(payslip.net)}</span></p>
      </div>
    </div>

    <div class="footer">
      <span>System generated by Alicesoft Payroll Engine</span>
      <span>Authorized Signature</span>
    </div>
  </div>
</body>
</html>`;

    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  return (
    <Modal open={open} title="Payslip" onClose={onClose}>
      {loading ? (
        <Skeleton height={220} />
      ) : payslip ? (
        <div className="stack-16">
          <div className="payslip-sheet">
            <div className="payslip-head">
              <div className="payslip-brand">
                <img src="/alicesoft-logo.png" alt="Alicesoft Logo" className="payslip-logo" />
                <div>
                  <h2>Alicesoft</h2>
                  <p className="muted">Salary Payslip</p>
                </div>
              </div>
              <div className="payslip-meta">
                <p>
                  <strong>Period:</strong> {payslip.month}
                </p>
                <p>
                  <strong>Employee ID:</strong> {payslip.employeeId}
                </p>
              </div>
            </div>

            <div className="payslip-grid">
              <section className="payslip-panel">
                <h4>Employee Details</h4>
                <div className="detail-grid">
                  <p>Name: {payslip.employeeName}</p>
                  <p>Role: {payslip.role}</p>
                  <p>Salary Model: {payslip.salaryModel}</p>
                  <p>Total Minutes: {payslip.totalMinutes}</p>
                  <p>Meals Consumed: {payslip.mealsConsumed}</p>
                </div>
              </section>

              <section className="payslip-panel">
                <h4>Deductions</h4>
                <div className="detail-grid">
                  <p>PF: {formatCurrency(payslip.pf)}</p>
                  <p>ESI: {formatCurrency(payslip.esi)}</p>
                  <p>PT: {formatCurrency(payslip.pt)}</p>
                  <p>TDS: {formatCurrency(payslip.tds)}</p>
                  <p>Meals: {formatCurrency(payslip.meals)}</p>
                </div>
              </section>
            </div>

            <section className="payslip-panel">
              <h4>Summary</h4>
              <div className="payroll-totals">
                <p>Gross: {formatCurrency(payslip.gross)}</p>
                <p>Deductions: {formatCurrency(payslip.deductions)}</p>
                <p>Net Pay (INR): {formatCurrency(payslip.net)}</p>
              </div>
            </section>

            <div className="payslip-footer">
              <p>Generated by Alicesoft Payroll Engine</p>
              <p>Authorized Signature</p>
            </div>
          </div>

          <div className="dialog-actions">
            <Button variant="secondary" onClick={handlePrintPdf}>
              Download PDF
            </Button>
          </div>
        </div>
      ) : (
        <p>No payslip data found.</p>
      )}
    </Modal>
  );
};
